preload = ~/.config/hypr/wallpapers/yuming-li-azure-symphony.jpg
#wallpaper =, ~/.config/hypr/wallpapers/yuming-li-azure-symphony.jpg

wallpaper{
	monitor = eDP-1
	path = /home/devich/.config/hypr/wallpapers/yuming-li-azure-symphony.jpg 
	fit_mode=cover
}

wallpaper{
	monitor = HDMI-A-1
	path = /home/devich/.config/hypr/wallpapers/ER_wallpaper0.jpeg
	fit_mode = cover
}
